//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.GodRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="GodRef.BibleWebserviceSoap")]
    public interface BibleWebserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetBibleWordsByChapterAndVerse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBibleWordsByChapterAndVerse(string BookTitle, int chapter, int Verse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetBibleWordsByChapterAndVerse", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBibleWordsByChapterAndVerseAsync(string BookTitle, int chapter, int Verse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetBibleWordsbyKeyWord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBibleWordsbyKeyWord(string BibleWords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetBibleWordsbyKeyWord", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBibleWordsbyKeyWordAsync(string BibleWords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetBookTitles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBookTitles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetBookTitles", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBookTitlesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetBibleWordsByBookTitleAndChapter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBibleWordsByBookTitleAndChapter(string BookTitle, int chapter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetBibleWordsByBookTitleAndChapter", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBibleWordsByBookTitleAndChapterAsync(string BookTitle, int chapter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BibleWebserviceSoapChannel : ConsoleApp.GodRef.BibleWebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BibleWebserviceSoapClient : System.ServiceModel.ClientBase<ConsoleApp.GodRef.BibleWebserviceSoap>, ConsoleApp.GodRef.BibleWebserviceSoap {
        
        public BibleWebserviceSoapClient() {
        }
        
        public BibleWebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BibleWebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BibleWebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BibleWebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetBibleWordsByChapterAndVerse(string BookTitle, int chapter, int Verse) {
            return base.Channel.GetBibleWordsByChapterAndVerse(BookTitle, chapter, Verse);
        }
        
        public System.Threading.Tasks.Task<string> GetBibleWordsByChapterAndVerseAsync(string BookTitle, int chapter, int Verse) {
            return base.Channel.GetBibleWordsByChapterAndVerseAsync(BookTitle, chapter, Verse);
        }
        
        public string GetBibleWordsbyKeyWord(string BibleWords) {
            return base.Channel.GetBibleWordsbyKeyWord(BibleWords);
        }
        
        public System.Threading.Tasks.Task<string> GetBibleWordsbyKeyWordAsync(string BibleWords) {
            return base.Channel.GetBibleWordsbyKeyWordAsync(BibleWords);
        }
        
        public string GetBookTitles() {
            return base.Channel.GetBookTitles();
        }
        
        public System.Threading.Tasks.Task<string> GetBookTitlesAsync() {
            return base.Channel.GetBookTitlesAsync();
        }
        
        public string GetBibleWordsByBookTitleAndChapter(string BookTitle, int chapter) {
            return base.Channel.GetBibleWordsByBookTitleAndChapter(BookTitle, chapter);
        }
        
        public System.Threading.Tasks.Task<string> GetBibleWordsByBookTitleAndChapterAsync(string BookTitle, int chapter) {
            return base.Channel.GetBibleWordsByBookTitleAndChapterAsync(BookTitle, chapter);
        }
    }
}
